//home页面头部 用户信息接口数据
let userApi = {
    "id": 99999,
    "code": "success",
    "result": true,
    "timestamp": "2022-01-20 15:45:37.683",
    "msg": "请求成功",
    "data": {
        "my": {
            "user": {
                "id": 751,
                "userNo": "4F34640058B84463B50379C391C3F742",
                "name": "请的",
                "account": "bbb",
                "passWord": " e10adc3949ba59abbe56e057f20f883e",
                "createTime": "2021-12-29 18:17:45",
                "statusName": "",
                "statusCode": "",
                "phone": "15996257153",
                "gender": "1",
                "position": "我是个职务",
                "email": "1402508703@qq.com",
                "isLeaderInDept": "0",
                "depId": "",
                "scrmStatus": 1,
                "userId": "Qing",
                "avatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
                "corpId": "wwc7f472208b21d67e",
                "status": 1,
                "wcstatus": 1,
                "isDelete": 0,
                "address": "",
                "accountType": "1",
                "remark": "",
                "lastTime": "2022-01-20 11:16:02",
                "creator": "",
                "departments": "超新的部门,又一个部门领导",
                "qrCode": "https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vc3f612ef1c7fdcf85",
                "mainDepartment": 7,
                "departmentName": null,
                "roleId": null,
                "roleName": null,
                "dataPermission": null
            },
            "custometMassUserSum": null,
            "custometMassSum": null,
            "friendSend": null,
            "friendSum": null,
            "customerSum": 73,
            "clueSum": 0,
            "groupSum": 8,
            "forReply": null,
            "forReplyCustomer": null,
            "newFollowCount": 0
        }
    }
}
//客户列表接口数据
let clientList = {
    "id": 99999,
    "code": "success",
    "result": true,
    "timestamp": "2022-01-20 16:36:26.197",
    "msg": "请求成功",
    "data": [
        {
            "id": 55240,
            "context": "更新了客户信息",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "请的",
            "createTime": "2022-01-20 16:36:06",
            "title": "更新客户信息",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "4F34640058B84463B50379C391C3F742",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 5,
            "optName": "更新客户信息",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "请的",
            "optAvatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": "[{\"联系人\": \"金雨\", \"历史联系人\": \"金雨\"}, {\"客户阶段\": \"\", \"历史客户阶段\": \"0000001413796804\"}]",
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 20000,
            "customerCalled": "金雨",
            "rowAt": 1
        },
        {
            "id": 55188,
            "context": "更新了客户信息",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "柏丽娟",
            "createTime": "2022-01-19 16:40:54",
            "title": "更新客户信息",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "2011368CCECC405BB385707D313B6DD3",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 5,
            "optName": "更新客户信息",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "柏丽娟",
            "optAvatar": "http://wework.qpic.cn/bizmail/oENxSwzFO8AKvHMR2gI8G5Y70cCY7PEZvlzhByIZHT4oGhg8Lw9IZA/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": "[{\"联系人\": \"金雨\", \"历史联系人\": \"金雨\"}, {\"客户阶段\": \"\", \"历史客户阶段\": \"0000001413796804\"}]",
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 86132000,
            "customerCalled": "金雨",
            "rowAt": 2
        },
        {
            "id": 55187,
            "context": "afdasdf",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "柏丽娟",
            "createTime": "2022-01-19 16:40:50",
            "title": "新增标签",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "2011368CCECC405BB385707D313B6DD3",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 26,
            "optName": "新增标签",
            "ossUrl": "",
            "ossObjectname": "afdasdf",
            "fromUser": "",
            "toUser": "",
            "optUserName": "柏丽娟",
            "optAvatar": "http://wework.qpic.cn/bizmail/oENxSwzFO8AKvHMR2gI8G5Y70cCY7PEZvlzhByIZHT4oGhg8Lw9IZA/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": null,
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 86136000,
            "customerCalled": "金雨",
            "rowAt": 3
        },
        {
            "id": 55186,
            "context": "更新了客户信息",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "柏丽娟",
            "createTime": "2022-01-19 16:40:07",
            "title": "更新客户信息",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "2011368CCECC405BB385707D313B6DD3",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 5,
            "optName": "更新客户信息",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "柏丽娟",
            "optAvatar": "http://wework.qpic.cn/bizmail/oENxSwzFO8AKvHMR2gI8G5Y70cCY7PEZvlzhByIZHT4oGhg8Lw9IZA/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": "[{\"联系人\": \"金雨\", \"历史联系人\": \"金雨\"}, {\"客户阶段\": \"\", \"历史客户阶段\": \"0000001413796804\"}]",
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 86179000,
            "customerCalled": "金雨",
            "rowAt": 4
        },
        {
            "id": 55185,
            "context": "添加为企业微信好友",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "柏丽娟",
            "createTime": "2022-01-19 16:38:45",
            "title": "添加企业微信好友",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "2011368CCECC405BB385707D313B6DD3",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 41,
            "optName": "添加企业微信好友",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "柏丽娟",
            "optAvatar": "http://wework.qpic.cn/bizmail/oENxSwzFO8AKvHMR2gI8G5Y70cCY7PEZvlzhByIZHT4oGhg8Lw9IZA/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": null,
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 86261000,
            "customerCalled": "金雨",
            "rowAt": 5
        },
        {
            "id": 55172,
            "context": "金雨-上海一样有限公司 添加协助人为 柏丽娟。",
            "clueCustomerNo": "682E07EF40D141C58CCB9F40CDCB6A59",
            "userName": "金雨",
            "createTime": "2022-01-19 16:32:47",
            "title": "新增协助人",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "04912100D13B40269B4D230DB6AFC451",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 18,
            "optName": "新增协助人",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "[{\"name\": \"柏丽娟\", \"depId\": \"上海一样有限公司\", \"avatar\": \"http://wework.qpic.cn/bizmail/oENxSwzFO8AKvHMR2gI8G5Y70cCY7PEZvlzhByIZHT4oGhg8Lw9IZA/0\", \"userId\": \"kristen\", \"userNo\": \"2011368CCECC405BB385707D313B6DD3\", \"permission\": 2}]",
            "optUserName": "金雨",
            "optAvatar": "https://wework.qpic.cn/bizmail/icLQhbUdbcGga9BWUw8SKHBicGh0kAYoeloFMoeaYgfxmKSalQZxWxiag/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": null,
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 86619000,
            "customerCalled": "金雨",
            "rowAt": 6
        },
        {
            "id": 55120,
            "context": "iui抑郁i",
            "clueCustomerNo": "948E15BD933644889153B9B7CA82B40F",
            "userName": "请的",
            "createTime": "2022-01-18 18:38:19",
            "title": "删除商机",
            "punckStatus": 3,
            "isDelete": 0,
            "createBy": "4F34640058B84463B50379C391C3F742",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 17,
            "optName": "删除商机",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "请的",
            "optAvatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": 115,
            "modifyContent": "[{\"商机名称\": \"iui抑郁i\"}, {\"商机金额\": \"0.00\"}, {\"预计成交时间\": \"2022-01-13\"}, {\"跟进阶段\": \"产测试\"}, {\"商机负责人\": \"请的\"}, {\"备注\": \"yuiy\"}]",
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 165487000,
            "customerCalled": "线索11",
            "rowAt": 1
        },
        {
            "id": 55118,
            "context": "商机",
            "clueCustomerNo": "BC1C20E11CC04F07992405DC1B711DE7",
            "userName": "请的",
            "createTime": "2022-01-18 18:37:39",
            "title": "删除商机",
            "punckStatus": 3,
            "isDelete": 0,
            "createBy": "4F34640058B84463B50379C391C3F742",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 17,
            "optName": "删除商机",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "请的",
            "optAvatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": 102,
            "modifyContent": "[{\"商机名称\": \"商机\"}, {\"商机金额\": \"0.00\"}, {\"预计成交时间\": \"2022-01-12\"}, {\"跟进阶段\": \"555\"}, {\"商机负责人\": \"Qing\"}, {\"备注\": \"\"}]",
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 165527000,
            "customerCalled": "达大厦大萨达撒大大所多萨达",
            "rowAt": 1
        },
        {
            "id": 55107,
            "context": "请的-超新的部门将这个线索转为客户了",
            "clueCustomerNo": "DFAB2B7BE07B43C09845E279A2F0CBC2",
            "userName": "请的",
            "createTime": "2022-01-18 17:58:08",
            "title": "线索转客户",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "4F34640058B84463B50379C391C3F742",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 4,
            "optName": "线索转客户",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "请的",
            "optAvatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": null,
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 167898000,
            "customerCalled": "线索15",
            "rowAt": 2
        },
        {
            "id": 55108,
            "context": "请的-超新的部门建立了客户:null 的档案",
            "clueCustomerNo": "DFAB2B7BE07B43C09845E279A2F0CBC2",
            "userName": "请的",
            "createTime": "2022-01-18 17:58:08",
            "title": "客户建档",
            "punckStatus": 6,
            "isDelete": 0,
            "createBy": "4F34640058B84463B50379C391C3F742",
            "isAll": null,
            "customerName": null,
            "praise": 0,
            "remarks": "",
            "optType": 5,
            "optName": "更新客户信息",
            "ossUrl": "",
            "ossObjectname": null,
            "fromUser": "",
            "toUser": "",
            "optUserName": "请的",
            "optAvatar": "http://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpxcI3KeSS7WZfLu07S3Ke1g/0",
            "commentCount": null,
            "dzFlag": null,
            "sourceId": null,
            "modifyContent": null,
            "optFlag": null,
            "optResult": null,
            "duration": null,
            "timeInterval": 167898000,
            "customerCalled": "线索15",
            "rowAt": 1
        }
    ]
}
//我的客户接口数据
let myClient = {
    "id": 99999,
    "code": "success",
    "result": true,
    "timestamp": "2022-01-20 16:46:27.134",
    "msg": "请求成功",
    "data": {
        "head": [
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 1,
                "records": [],
                "searchCount": true,
                "columnValue": "customerCalled",
                "priority": 1,
                "defaultEnableStatus": true,
                "version": 0,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24544,
                "enableStatus": true,
                "columnName": "客户名称"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 2,
                "records": [],
                "modifyUserId": 204,
                "searchCount": true,
                "columnValue": "stage",
                "priority": 2,
                "defaultEnableStatus": true,
                "version": 24,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "modifyTime": 1642492686000,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24545,
                "enableStatus": true,
                "columnName": "客户阶段"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 3,
                "records": [],
                "modifyUserId": 204,
                "searchCount": true,
                "columnValue": "source",
                "priority": 3,
                "defaultEnableStatus": true,
                "version": 16,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "modifyTime": 1642506197000,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24546,
                "enableStatus": true,
                "columnName": "客户来源"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 6,
                "records": [],
                "searchCount": true,
                "columnValue": "name",
                "priority": 6,
                "defaultEnableStatus": true,
                "version": 0,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24549,
                "enableStatus": true,
                "columnName": "联系人"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 9,
                "records": [],
                "searchCount": true,
                "columnValue": "phone",
                "priority": 9,
                "defaultEnableStatus": true,
                "version": 0,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24552,
                "enableStatus": true,
                "columnName": "手机号码"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 12,
                "records": [],
                "searchCount": true,
                "columnValue": "userNo",
                "priority": 12,
                "defaultEnableStatus": true,
                "version": 0,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24555,
                "enableStatus": true,
                "columnName": "负责人"
            },
            {
                "createUserId": -1,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 15,
                "records": [],
                "searchCount": true,
                "columnValue": "createTime",
                "priority": 15,
                "defaultEnableStatus": true,
                "version": 0,
                "columnType": 0,
                "current": 1,
                "total": 0,
                "pages": 0,
                "size": 10,
                "createTime": 1640773890000,
                "orders": [],
                "id": 24558,
                "enableStatus": true,
                "columnName": "建档时间"
            },
            {
                "createUserId": 214,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 1,
                "records": [],
                "modifyUserId": 209,
                "searchCount": true,
                "columnValue": "wenben111111",
                "priority": 1,
                "defaultEnableStatus": false,
                "version": 4,
                "columnType": 1,
                "current": 1,
                "total": 0,
                "modifyTime": 1640165885000,
                "pages": 0,
                "size": 10,
                "createTime": 1638710275000,
                "orders": [],
                "id": 19291,
                "enableStatus": true,
                "columnName": "文本111111"
            },
            {
                "createUserId": 214,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 2,
                "records": [],
                "modifyUserId": 214,
                "searchCount": true,
                "columnValue": "xuanze11",
                "priority": 2,
                "defaultEnableStatus": false,
                "version": 1,
                "columnType": 2,
                "current": 1,
                "total": 0,
                "modifyTime": 1638710292000,
                "pages": 0,
                "size": 10,
                "createTime": 1638710290000,
                "optionsVOList": [
                    {
                        "createUserId": 214,
                        "corpId": "wwc7f472208b21d67e",
                        "optimizeCountSql": true,
                        "records": [],
                        "searchCount": true,
                        "columnValue": "xuanze11",
                        "version": 0,
                        "columnOption": "111",
                        "current": 1,
                        "total": 0,
                        "pages": 0,
                        "size": 10,
                        "createTime": 1638710290000,
                        "orders": [],
                        "id": 113
                    },
                    {
                        "createUserId": 214,
                        "corpId": "wwc7f472208b21d67e",
                        "optimizeCountSql": true,
                        "records": [],
                        "searchCount": true,
                        "columnValue": "xuanze11",
                        "version": 0,
                        "columnOption": "222",
                        "current": 1,
                        "total": 0,
                        "pages": 0,
                        "size": 10,
                        "createTime": 1638710290000,
                        "orders": [],
                        "id": 114
                    }
                ],
                "orders": [],
                "id": 19292,
                "enableStatus": true,
                "columnName": "选择11"
            },
            {
                "createUserId": 214,
                "corpId": "wwc7f472208b21d67e",
                "optimizeCountSql": true,
                "defaultPriority": 3,
                "records": [],
                "modifyUserId": 209,
                "searchCount": true,
                "columnValue": "shijian11",
                "priority": 3,
                "defaultEnableStatus": false,
                "version": 4,
                "columnType": 3,
                "current": 1,
                "total": 0,
                "modifyTime": 1640079552000,
                "pages": 0,
                "size": 10,
                "createTime": 1638710323000,
                "orders": [],
                "id": 19293,
                "enableStatus": true,
                "columnName": "时间11"
            }
        ],
        "iPage": {
            "current": 1,
            "total": 73,
            "pages": 8,
            "optimizeCountSql": true,
            "size": 10,
            "records": [
                {
                    "clueType": "主动创建",
                    "externalType": 0,
                    "beBelongBy": "",
                    "gender": "",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "官网",
                    "mobil": "",
                    "clueCustomerNo": "A1605489233045D696C61BD517583A47",
                    "customerType": "其他",
                    "turnTime": 1642492692000,
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 42097,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "address": "3333",
                    "uname": "请的",
                    "genMethod": "线索转客户",
                    "isWcCus": 0,
                    "customerTagNames": [
                        "测试标签组:444444444444444",
                        "手动阀"
                    ],
                    "cropFullName": "333",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "",
                    "customerName": "",
                    "externalSource": "未知来源",
                    "customerCalled": "12",
                    "createBy": "请的",
                    "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
                    "followTime": 1642493083000,
                    "weixin": "",
                    "stage": "沟通洽谈",
                    "createTime": 1642473694000,
                    "phone": "19935934957",
                    "name": "3333",
                    "wechatNickname": "",
                    "externalUseridIn": "",
                    "describe": "",
                    "position": "",
                    "followRecord": "手动阀",
                    "corpScale": "1001及以上"
                },
                {
                    "clueType": "加微线索",
                    "externalType": 2,
                    "beBelongBy": "",
                    "gender": "2",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "5BD51B98D6D34AA7AB871901406CC614",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 42076,
                    "followrole": "1",
                    "email": "",
                    "followUserNames": "",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "其他",
                    "isWcCus": 1,
                    "cropFullName": "上海极洲互动信息科技有限公司",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "http://wework.qpic.cn/wwhead/duc2TvpEgSSdsPInfahzx9g1gKWw7ea6ib9C24AOWy4lgMd84SkHkXzyt3AgR5YrG5syDAF0FZAs/0",
                    "customerName": "极洲互动",
                    "externalSource": "扫描二维码",
                    "customerCalled": "极洲客服",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642192728000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642192728000,
                    "phone": "",
                    "name": "极洲客服",
                    "wechatNickname": "",
                    "externalUseridIn": "woyPDZEQAAQzAwhtZuSIbrU3zN5DQB3g",
                    "describe": "",
                    "position": "",
                    "followRecord": ""
                },
                {
                    "clueType": "加微线索",
                    "externalType": 2,
                    "beBelongBy": "",
                    "gender": "1",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "ED3CFB4697DC4730968C85FCB8318603",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 42025,
                    "followrole": "1",
                    "email": "",
                    "followUserNames": "",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "其他",
                    "isWcCus": 1,
                    "cropFullName": "",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "https://wework.qpic.cn/bizmail/maz9BQvyyINzDvpLWfUEIOWXR6rAdkfOAJSsO7Fn4985xaqdBvtWGg/0",
                    "customerName": "hand cream",
                    "externalSource": "扫描二维码",
                    "customerCalled": "殷本稳",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642176734000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642176734000,
                    "phone": "",
                    "name": "殷本稳",
                    "wechatNickname": "",
                    "externalUseridIn": "woyPDZEQAADeS2PcS0l9MBOnHGrgBMhw",
                    "describe": "",
                    "position": "",
                    "followRecord": ""
                },
                {
                    "clueType": "加微线索",
                    "externalType": 2,
                    "beBelongBy": "",
                    "gender": "1",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "2D4B589E9A2E466FB6025A2F544AEC2B",
                    "customerType": "其他",
                    "turnTime": 1642175200000,
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 42024,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "opportunitiesEntities": [
                        {
                            "chargeUserName": "请的",
                            "corpId": "wwc7f472208b21d67e",
                            "endRemarks": "",
                            "expectEndTime": 1641916800000,
                            "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                            "createUserNo": "4F34640058B84463B50379C391C3F742",
                            "deleted": false,
                            "createTime": 1642187797000,
                            "price": 0,
                            "name": "44454",
                            "stageNo": 3,
                            "id": 146,
                            "customerNo": "2D4B589E9A2E466FB6025A2F544AEC2B",
                            "remarks": "",
                            "status": 0,
                            "updateUserNo": "4F34640058B84463B50379C391C3F742"
                        }
                    ],
                    "clueTagName": "来源:天空",
                    "address": "222",
                    "uname": "请的",
                    "genMethod": "线索转客户",
                    "isWcCus": 1,
                    "customerTagNames": [
                        "广东省43214",
                        "asdfdsa",
                        "手动阀",
                        "dsada:8",
                        "测试标签组:444444444444444",
                        "测试标签组:666666666666666",
                        "测试标签组:测试标签",
                        "测试标签组:w的味道",
                        "测试标签组:策划",
                        "测试标签组:标签",
                        "0000:hhhh",
                        "哈哈哈哈哈:000",
                        "哈哈哈哈哈:1"
                    ],
                    "cropFullName": "1111",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "https://wework.qpic.cn/wwhead/nMl9ssowtibVGyrmvBiaibzDtYianvZibribWJD2SsTukFg9956IbL5ibJg3hm3gxMsSJKbtNiczHVLia28c/0",
                    "customerName": "柯基科技",
                    "externalSource": "扫描二维码",
                    "customerCalled": "袁",
                    "createBy": "请的",
                    "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
                    "followTime": 1642492609000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642170741000,
                    "phone": "19898787676",
                    "name": "袁",
                    "wechatNickname": "",
                    "externalUseridIn": "woyPDZEQAA-oPy8A5QYC3hc_WKmTWxPA",
                    "describe": "",
                    "position": "",
                    "followRecord": "asdfdsa,手动阀",
                    "corpScale": "1-50人"
                },
                {
                    "clueType": "加微线索",
                    "externalType": 2,
                    "beBelongBy": "",
                    "gender": "1",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "F482D647BE3D464CA74150E485BD1876",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41914,
                    "followrole": "1",
                    "email": "",
                    "followUserNames": "",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "其他",
                    "isWcCus": 1,
                    "customerTagNames": [
                        "dsada:7"
                    ],
                    "cropFullName": "",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "https://wx.qlogo.cn/mmhead/04LrpEqAf4vAjHiagpAqV47r6CEXiaial5WMqwPXpZecMs2ZZBhg96rJw/0",
                    "customerName": "上海默认企业",
                    "externalSource": "扫描二维码",
                    "customerCalled": "赵春艳",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642170382000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642057034000,
                    "phone": "",
                    "name": "赵春艳",
                    "wechatNickname": "",
                    "externalUseridIn": "woyPDZEQAArRhHnMYY0XvBbGw0gViHkg",
                    "describe": "",
                    "position": "",
                    "followRecord": "个人标签,aaa"
                },
                {
                    "clueType": "主动创建",
                    "externalType": 0,
                    "beBelongBy": "",
                    "gender": "",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "官网",
                    "mobil": "",
                    "clueCustomerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                    "customerType": "其他",
                    "turnTime": 1642043271000,
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41909,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "opportunitiesEntities": [
                        {
                            "chargeUserName": "请的",
                            "corpId": "wwc7f472208b21d67e",
                            "endRemarks": "",
                            "expectEndTime": 1641398400000,
                            "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                            "createUserNo": "4F34640058B84463B50379C391C3F742",
                            "updateTime": 1642152463000,
                            "deleted": false,
                            "createTime": 1642046432000,
                            "price": 0,
                            "name": "饿我去恶趣味",
                            "stageNo": 1,
                            "endTime": 1642003200000,
                            "id": 116,
                            "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                            "remarks": "",
                            "status": 1,
                            "updateUserNo": "4F34640058B84463B50379C391C3F742"
                        },
                        {
                            "chargeUserName": "请的",
                            "corpId": "wwc7f472208b21d67e",
                            "endRemarks": "",
                            "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                            "createUserNo": "4F34640058B84463B50379C391C3F742",
                            "deleted": false,
                            "createTime": 1642043603000,
                            "price": 0,
                            "name": "342423",
                            "stageNo": 2,
                            "id": 109,
                            "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                            "remarks": "32423",
                            "status": 0
                        },
                        {
                            "chargeUserName": "请的",
                            "corpId": "wwc7f472208b21d67e",
                            "endRemarks": "",
                            "expectEndTime": 1642003200000,
                            "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                            "createUserNo": "4F34640058B84463B50379C391C3F742",
                            "updateTime": 1642043581000,
                            "deleted": false,
                            "createTime": 1642043571000,
                            "price": 0,
                            "name": "4234234",
                            "stageNo": 1,
                            "endTime": 1642003200000,
                            "id": 108,
                            "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                            "remarks": "",
                            "status": 1,
                            "updateUserNo": "4F34640058B84463B50379C391C3F742"
                        }
                    ],
                    "address": "2233",
                    "uname": "请的",
                    "genMethod": "线索转客户",
                    "isWcCus": 0,
                    "cropFullName": "1",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "",
                    "customerName": "",
                    "externalSource": "未知来源",
                    "customerCalled": "19",
                    "createBy": "请的",
                    "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
                    "followTime": 1642166557000,
                    "weixin": "",
                    "stage": "沟通洽谈",
                    "createTime": 1642043219000,
                    "phone": "19989988787",
                    "name": "32131",
                    "wechatNickname": "",
                    "externalUseridIn": "",
                    "describe": "",
                    "position": "",
                    "followRecord": "aaaaaa",
                    "corpScale": "1-50人"
                },
                {
                    "clueType": "主动创建",
                    "externalType": 2,
                    "beBelongBy": "",
                    "gender": "0",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "1669B183024840DEA164DF9842B0E904",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41906,
                    "followrole": "1",
                    "email": "",
                    "followUserNames": "",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "其他",
                    "isWcCus": 1,
                    "cropFullName": "",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "https://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpVRHsj01mgCTggxrQblovQw/0",
                    "customerName": "柯基科技",
                    "externalSource": "扫描二维码",
                    "customerCalled": "姚天雷",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642058290000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642042835000,
                    "phone": "",
                    "name": "姚天雷",
                    "wechatNickname": "",
                    "externalUseridIn": "woyPDZEQAAHvi7PhHr1Lh5TSrN4WV5BA",
                    "describe": "",
                    "position": "",
                    "followRecord": "请的-超新的部门 新增标签为 问问 。"
                },
                {
                    "clueType": "线索导入",
                    "externalType": 0,
                    "beBelongBy": "",
                    "gender": "0",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "9D96477B8368401F892032C221F9D1C2",
                    "customerType": "其他",
                    "turnTime": 1642043500000,
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41890,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "opportunitiesEntities": [
                        {
                            "chargeUserName": "请的",
                            "corpId": "wwc7f472208b21d67e",
                            "endRemarks": "",
                            "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                            "createUserNo": "4F34640058B84463B50379C391C3F742",
                            "updateTime": 1642046268000,
                            "endReasonId": 21,
                            "deleted": false,
                            "createTime": 1642046259000,
                            "price": 0,
                            "name": "57657",
                            "stageNo": 1,
                            "id": 113,
                            "customerNo": "9D96477B8368401F892032C221F9D1C2",
                            "remarks": "7675",
                            "status": 3,
                            "updateUserNo": "4F34640058B84463B50379C391C3F742"
                        }
                    ],
                    "clueTagName": "来源:导入",
                    "address": "3423423",
                    "uname": "请的",
                    "genMethod": "线索转客户",
                    "isWcCus": 0,
                    "cropFullName": "829849394",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "",
                    "customerName": "",
                    "externalSource": "未知来源",
                    "customerCalled": "线索8",
                    "createBy": "请的",
                    "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
                    "followTime": 1642043500000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642042204000,
                    "phone": "19792337473",
                    "name": "32423423",
                    "wechatNickname": "",
                    "externalUseridIn": "",
                    "describe": "",
                    "position": "",
                    "followRecord": "请的-超新的部门建立了客户:null 的档案",
                    "corpScale": "1001及以上"
                },
                {
                    "clueType": "线索导入",
                    "externalType": 0,
                    "beBelongBy": "",
                    "gender": "0",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "A02C2DB40C264E89B471D30BFB66517B",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41889,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "clueTagName": "来源:导入",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "客户导入",
                    "isWcCus": 0,
                    "cropFullName": "",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "",
                    "customerName": "",
                    "externalSource": "未知来源",
                    "customerCalled": "线索7",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642042203000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642042204000,
                    "phone": "",
                    "name": "",
                    "wechatNickname": "",
                    "externalUseridIn": "",
                    "describe": "",
                    "position": "",
                    "followRecord": ""
                },
                {
                    "clueType": "线索导入",
                    "externalType": 0,
                    "beBelongBy": "",
                    "gender": "0",
                    "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
                    "userNo": "请的",
                    "remark": "",
                    "source": "陌拜",
                    "mobil": "",
                    "clueCustomerNo": "B1AFDC04EE3C49BB89E6E4B1CF9CC0D6",
                    "customerType": "其他",
                    "updateBy": "",
                    "beBelongNo": "",
                    "id": 41885,
                    "followrole": "1",
                    "email": "",
                    "corpCustomColumnMap": {
                        "wenben111111": "",
                        "xuanze11": "",
                        "shijian11": ""
                    },
                    "followUserNames": "",
                    "clueTagName": "来源:导入",
                    "address": "",
                    "uname": "请的",
                    "genMethod": "客户导入",
                    "isWcCus": 0,
                    "cropFullName": "",
                    "deps": "超新的部门,又一个部门领导",
                    "avatar": "",
                    "customerName": "",
                    "externalSource": "未知来源",
                    "customerCalled": "线索3",
                    "createBy": "请的",
                    "cropSubIndustry": "",
                    "followTime": 1642042203000,
                    "weixin": "",
                    "stage": "意向客户",
                    "createTime": 1642042204000,
                    "phone": "",
                    "name": "",
                    "wechatNickname": "",
                    "externalUseridIn": "",
                    "describe": "",
                    "position": "",
                    "followRecord": ""
                }
            ],
            "searchCount": true,
            "orders": []
        }
    }
}
export {
    userApi,
    clientList,
    myClient
}

