//home页面头部 用户信息接口数据
let list = {
    "id": 99999,
    "code": "success",
    "result": true,
    "timestamp": "2022-01-20 17:08:03.512",
    "msg": "请求成功",
    "data": {
      "head": [
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 1,
          "records": [],
          "searchCount": true,
          "columnValue": "customerCalled",
          "priority": 1,
          "defaultEnableStatus": true,
          "version": 0,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24544,
          "enableStatus": true,
          "columnName": "客户名称"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 2,
          "records": [],
          "modifyUserId": 204,
          "searchCount": true,
          "columnValue": "stage",
          "priority": 2,
          "defaultEnableStatus": true,
          "version": 24,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "modifyTime": 1642492686000,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24545,
          "enableStatus": true,
          "columnName": "客户阶段"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 3,
          "records": [],
          "modifyUserId": 204,
          "searchCount": true,
          "columnValue": "source",
          "priority": 3,
          "defaultEnableStatus": true,
          "version": 16,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "modifyTime": 1642506197000,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24546,
          "enableStatus": true,
          "columnName": "客户来源"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 6,
          "records": [],
          "searchCount": true,
          "columnValue": "name",
          "priority": 6,
          "defaultEnableStatus": true,
          "version": 0,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24549,
          "enableStatus": true,
          "columnName": "联系人"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 9,
          "records": [],
          "searchCount": true,
          "columnValue": "phone",
          "priority": 9,
          "defaultEnableStatus": true,
          "version": 0,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24552,
          "enableStatus": true,
          "columnName": "手机号码"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 12,
          "records": [],
          "searchCount": true,
          "columnValue": "userNo",
          "priority": 12,
          "defaultEnableStatus": true,
          "version": 0,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24555,
          "enableStatus": true,
          "columnName": "负责人"
        },
        {
          "createUserId": -1,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 15,
          "records": [],
          "searchCount": true,
          "columnValue": "createTime",
          "priority": 15,
          "defaultEnableStatus": true,
          "version": 0,
          "columnType": 0,
          "current": 1,
          "total": 0,
          "pages": 0,
          "size": 10,
          "createTime": 1640773890000,
          "orders": [],
          "id": 24558,
          "enableStatus": true,
          "columnName": "建档时间"
        },
        {
          "createUserId": 214,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 1,
          "records": [],
          "modifyUserId": 209,
          "searchCount": true,
          "columnValue": "wenben111111",
          "priority": 1,
          "defaultEnableStatus": false,
          "version": 4,
          "columnType": 1,
          "current": 1,
          "total": 0,
          "modifyTime": 1640165885000,
          "pages": 0,
          "size": 10,
          "createTime": 1638710275000,
          "orders": [],
          "id": 19291,
          "enableStatus": true,
          "columnName": "文本111111"
        },
        {
          "createUserId": 214,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 2,
          "records": [],
          "modifyUserId": 214,
          "searchCount": true,
          "columnValue": "xuanze11",
          "priority": 2,
          "defaultEnableStatus": false,
          "version": 1,
          "columnType": 2,
          "current": 1,
          "total": 0,
          "modifyTime": 1638710292000,
          "pages": 0,
          "size": 10,
          "createTime": 1638710290000,
          "optionsVOList": [
            {
              "createUserId": 214,
              "corpId": "wwc7f472208b21d67e",
              "optimizeCountSql": true,
              "records": [],
              "searchCount": true,
              "columnValue": "xuanze11",
              "version": 0,
              "columnOption": "111",
              "current": 1,
              "total": 0,
              "pages": 0,
              "size": 10,
              "createTime": 1638710290000,
              "orders": [],
              "id": 113
            },
            {
              "createUserId": 214,
              "corpId": "wwc7f472208b21d67e",
              "optimizeCountSql": true,
              "records": [],
              "searchCount": true,
              "columnValue": "xuanze11",
              "version": 0,
              "columnOption": "222",
              "current": 1,
              "total": 0,
              "pages": 0,
              "size": 10,
              "createTime": 1638710290000,
              "orders": [],
              "id": 114
            }
          ],
          "orders": [],
          "id": 19292,
          "enableStatus": true,
          "columnName": "选择11"
        },
        {
          "createUserId": 214,
          "corpId": "wwc7f472208b21d67e",
          "optimizeCountSql": true,
          "defaultPriority": 3,
          "records": [],
          "modifyUserId": 209,
          "searchCount": true,
          "columnValue": "shijian11",
          "priority": 3,
          "defaultEnableStatus": false,
          "version": 4,
          "columnType": 3,
          "current": 1,
          "total": 0,
          "modifyTime": 1640079552000,
          "pages": 0,
          "size": 10,
          "createTime": 1638710323000,
          "orders": [],
          "id": 19293,
          "enableStatus": true,
          "columnName": "时间11"
        }
      ],
      "iPage": {
        "current": 1,
        "total": 73,
        "pages": 4,
        "optimizeCountSql": true,
        "size": 20,
        "records": [
          {
            "clueType": "主动创建",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "官网",
            "mobil": "",
            "clueCustomerNo": "A1605489233045D696C61BD517583A47",
            "customerType": "其他",
            "turnTime": 1642492692000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 42097,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "address": "3333",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "customerTagNames": [
              "测试标签组:444444444444444",
              "手动阀"
            ],
            "cropFullName": "333",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "12",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642493083000,
            "weixin": "",
            "stage": "沟通洽谈",
            "createTime": 1642473694000,
            "phone": "19935934957",
            "name": "3333",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "手动阀",
            "corpScale": "1001及以上"
          },
          {
            "clueType": "加微线索",
            "externalType": 2,
            "beBelongBy": "",
            "gender": "2",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "5BD51B98D6D34AA7AB871901406CC614",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 42076,
            "followrole": "1",
            "email": "",
            "followUserNames": "",
            "address": "",
            "uname": "请的",
            "genMethod": "其他",
            "isWcCus": 1,
            "cropFullName": "上海极洲互动信息科技有限公司",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "http://wework.qpic.cn/wwhead/duc2TvpEgSSdsPInfahzx9g1gKWw7ea6ib9C24AOWy4lgMd84SkHkXzyt3AgR5YrG5syDAF0FZAs/0",
            "customerName": "极洲互动",
            "externalSource": "扫描二维码",
            "customerCalled": "极洲客服",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642192728000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642192728000,
            "phone": "",
            "name": "极洲客服",
            "wechatNickname": "",
            "externalUseridIn": "woyPDZEQAAQzAwhtZuSIbrU3zN5DQB3g",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "加微线索",
            "externalType": 2,
            "beBelongBy": "",
            "gender": "1",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "ED3CFB4697DC4730968C85FCB8318603",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 42025,
            "followrole": "1",
            "email": "",
            "followUserNames": "",
            "address": "",
            "uname": "请的",
            "genMethod": "其他",
            "isWcCus": 1,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "https://wework.qpic.cn/bizmail/maz9BQvyyINzDvpLWfUEIOWXR6rAdkfOAJSsO7Fn4985xaqdBvtWGg/0",
            "customerName": "hand cream",
            "externalSource": "扫描二维码",
            "customerCalled": "殷本稳",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642176734000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642176734000,
            "phone": "",
            "name": "殷本稳",
            "wechatNickname": "",
            "externalUseridIn": "woyPDZEQAADeS2PcS0l9MBOnHGrgBMhw",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "加微线索",
            "externalType": 2,
            "beBelongBy": "",
            "gender": "1",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "2D4B589E9A2E466FB6025A2F544AEC2B",
            "customerType": "其他",
            "turnTime": 1642175200000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 42024,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "opportunitiesEntities": [
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "expectEndTime": 1641916800000,
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "deleted": false,
                "createTime": 1642187797000,
                "price": 0,
                "name": "44454",
                "stageNo": 3,
                "id": 146,
                "customerNo": "2D4B589E9A2E466FB6025A2F544AEC2B",
                "remarks": "",
                "status": 0,
                "updateUserNo": "4F34640058B84463B50379C391C3F742"
              }
            ],
            "clueTagName": "来源:天空",
            "address": "222",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 1,
            "customerTagNames": [
              "广东省43214",
              "asdfdsa",
              "手动阀",
              "dsada:8",
              "测试标签组:444444444444444",
              "测试标签组:666666666666666",
              "测试标签组:测试标签",
              "测试标签组:w的味道",
              "测试标签组:策划",
              "测试标签组:标签",
              "0000:hhhh",
              "哈哈哈哈哈:000",
              "哈哈哈哈哈:1"
            ],
            "cropFullName": "1111",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "https://wework.qpic.cn/wwhead/nMl9ssowtibVGyrmvBiaibzDtYianvZibribWJD2SsTukFg9956IbL5ibJg3hm3gxMsSJKbtNiczHVLia28c/0",
            "customerName": "柯基科技",
            "externalSource": "扫描二维码",
            "customerCalled": "袁",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642492609000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642170741000,
            "phone": "19898787676",
            "name": "袁",
            "wechatNickname": "",
            "externalUseridIn": "woyPDZEQAA-oPy8A5QYC3hc_WKmTWxPA",
            "describe": "",
            "position": "",
            "followRecord": "asdfdsa,手动阀",
            "corpScale": "1-50人"
          },
          {
            "clueType": "加微线索",
            "externalType": 2,
            "beBelongBy": "",
            "gender": "1",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "F482D647BE3D464CA74150E485BD1876",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41914,
            "followrole": "1",
            "email": "",
            "followUserNames": "",
            "address": "",
            "uname": "请的",
            "genMethod": "其他",
            "isWcCus": 1,
            "customerTagNames": [
              "dsada:7"
            ],
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "https://wx.qlogo.cn/mmhead/04LrpEqAf4vAjHiagpAqV47r6CEXiaial5WMqwPXpZecMs2ZZBhg96rJw/0",
            "customerName": "上海默认企业",
            "externalSource": "扫描二维码",
            "customerCalled": "赵春艳",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642170382000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642057034000,
            "phone": "",
            "name": "赵春艳",
            "wechatNickname": "",
            "externalUseridIn": "woyPDZEQAArRhHnMYY0XvBbGw0gViHkg",
            "describe": "",
            "position": "",
            "followRecord": "个人标签,aaa"
          },
          {
            "clueType": "主动创建",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "官网",
            "mobil": "",
            "clueCustomerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
            "customerType": "其他",
            "turnTime": 1642043271000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41909,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "opportunitiesEntities": [
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "expectEndTime": 1641398400000,
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "updateTime": 1642152463000,
                "deleted": false,
                "createTime": 1642046432000,
                "price": 0,
                "name": "饿我去恶趣味",
                "stageNo": 1,
                "endTime": 1642003200000,
                "id": 116,
                "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                "remarks": "",
                "status": 1,
                "updateUserNo": "4F34640058B84463B50379C391C3F742"
              },
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "deleted": false,
                "createTime": 1642043603000,
                "price": 0,
                "name": "342423",
                "stageNo": 2,
                "id": 109,
                "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                "remarks": "32423",
                "status": 0
              },
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "expectEndTime": 1642003200000,
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "updateTime": 1642043581000,
                "deleted": false,
                "createTime": 1642043571000,
                "price": 0,
                "name": "4234234",
                "stageNo": 1,
                "endTime": 1642003200000,
                "id": 108,
                "customerNo": "148C95EDC2D5417FA2EB5EA1ABEEA861",
                "remarks": "",
                "status": 1,
                "updateUserNo": "4F34640058B84463B50379C391C3F742"
              }
            ],
            "address": "2233",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "1",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "19",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642166557000,
            "weixin": "",
            "stage": "沟通洽谈",
            "createTime": 1642043219000,
            "phone": "19989988787",
            "name": "32131",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "aaaaaa",
            "corpScale": "1-50人"
          },
          {
            "clueType": "主动创建",
            "externalType": 2,
            "beBelongBy": "",
            "gender": "0",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "1669B183024840DEA164DF9842B0E904",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41906,
            "followrole": "1",
            "email": "",
            "followUserNames": "",
            "address": "",
            "uname": "请的",
            "genMethod": "其他",
            "isWcCus": 1,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "https://wework.qpic.cn/bizmail/WqicNrlSFrvwpWZwjiccTfh3ecJUofEJYpVRHsj01mgCTggxrQblovQw/0",
            "customerName": "柯基科技",
            "externalSource": "扫描二维码",
            "customerCalled": "姚天雷",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642058290000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042835000,
            "phone": "",
            "name": "姚天雷",
            "wechatNickname": "",
            "externalUseridIn": "woyPDZEQAAHvi7PhHr1Lh5TSrN4WV5BA",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门 新增标签为 问问 。"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "7C5068BDF564426B9D7A35CF39E56EE4",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41886,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索4",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "34D04D69FCBF4EBD9CE45A0CE69BEDCF",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41900,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索18",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "76E810A93B4842D9AA175ED0AC67F711",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41902,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索20",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "948E15BD933644889153B9B7CA82B40F",
            "customerType": "其他",
            "turnTime": 1642043330000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41893,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "756756",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "565",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索11",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642043330000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "18797776676",
            "name": "567567",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门建立了客户:null 的档案",
            "corpScale": "1-50人"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "4DF28912F49445B6ADCF4A3B465CD401",
            "customerType": "其他",
            "turnTime": 1642043367000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41892,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "opportunitiesEntities": [
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "deleted": false,
                "createTime": 1642046291000,
                "price": 0,
                "name": "ui意义",
                "stageNo": 1,
                "id": 114,
                "customerNo": "4DF28912F49445B6ADCF4A3B465CD401",
                "remarks": "以再",
                "status": 0
              }
            ],
            "clueTagName": "来源:导入",
            "address": "464363463",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "54543634",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索10",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642473244000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "19978778676",
            "name": "654656",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门 移除标签为 aaa 。",
            "corpScale": "1-50人"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "0C1A3EAFB8C8427CA9C3D65D124787B1",
            "customerType": "其他",
            "turnTime": 1642043443000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41891,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "5345453",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "34534534",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索9",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642043443000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "18989757345",
            "name": "5345345",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门建立了客户:null 的档案",
            "corpScale": "1001及以上"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "9D96477B8368401F892032C221F9D1C2",
            "customerType": "其他",
            "turnTime": 1642043500000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41890,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "opportunitiesEntities": [
              {
                "chargeUserName": "请的",
                "corpId": "wwc7f472208b21d67e",
                "endRemarks": "",
                "chargeUserNo": "4F34640058B84463B50379C391C3F742",
                "createUserNo": "4F34640058B84463B50379C391C3F742",
                "updateTime": 1642046268000,
                "endReasonId": 21,
                "deleted": false,
                "createTime": 1642046259000,
                "price": 0,
                "name": "57657",
                "stageNo": 1,
                "id": 113,
                "customerNo": "9D96477B8368401F892032C221F9D1C2",
                "remarks": "7675",
                "status": 3,
                "updateUserNo": "4F34640058B84463B50379C391C3F742"
              }
            ],
            "clueTagName": "来源:导入",
            "address": "3423423",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "829849394",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索8",
            "createBy": "请的",
            "cropSubIndustry": "IT服务/计算机软件/硬件/信息服务",
            "followTime": 1642043500000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "19792337473",
            "name": "32423423",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门建立了客户:null 的档案",
            "corpScale": "1001及以上"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "A02C2DB40C264E89B471D30BFB66517B",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41889,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索7",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "C8EA81683C2044C699860352FEB7D659",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41888,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索6",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "09D03810EA434DFCA0E93BE136197649",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41887,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索5",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "910B83C26F85407F9BB761B83AE9FD28",
            "customerType": "其他",
            "turnTime": 1642473319000,
            "updateBy": "",
            "beBelongNo": "",
            "id": 41898,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "1212",
            "uname": "请的",
            "genMethod": "线索转客户",
            "isWcCus": 0,
            "cropFullName": "12",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索16",
            "createBy": "请的",
            "cropSubIndustry": "文化/体育/娱乐业/其他",
            "followTime": 1642473319000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "19937483472",
            "name": "1231",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": "请的-超新的部门建立了客户:null 的档案",
            "corpScale": "1001及以上"
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "B1AFDC04EE3C49BB89E6E4B1CF9CC0D6",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41885,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索3",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          },
          {
            "clueType": "线索导入",
            "externalType": 0,
            "beBelongBy": "",
            "gender": "0",
            "corpCustomColumn": "{\"xuanze11\": \"\", \"shijian11\": \"\", \"wenben111111\": \"\"}",
            "userNo": "请的",
            "remark": "",
            "source": "陌拜",
            "mobil": "",
            "clueCustomerNo": "9DA948F0E5B144688CA5F0B4942B6977",
            "customerType": "其他",
            "updateBy": "",
            "beBelongNo": "",
            "id": 41884,
            "followrole": "1",
            "email": "",
            "corpCustomColumnMap": {
              "wenben111111": "",
              "xuanze11": "",
              "shijian11": ""
            },
            "followUserNames": "",
            "clueTagName": "来源:导入",
            "address": "",
            "uname": "请的",
            "genMethod": "客户导入",
            "isWcCus": 0,
            "cropFullName": "",
            "deps": "超新的部门,又一个部门领导",
            "avatar": "",
            "customerName": "",
            "externalSource": "未知来源",
            "customerCalled": "线索2",
            "createBy": "请的",
            "cropSubIndustry": "",
            "followTime": 1642042203000,
            "weixin": "",
            "stage": "意向客户",
            "createTime": 1642042204000,
            "phone": "",
            "name": "",
            "wechatNickname": "",
            "externalUseridIn": "",
            "describe": "",
            "position": "",
            "followRecord": ""
          }
        ],
        "searchCount": true,
        "orders": []
      }
    }
  }
//客户列表接口数据
let clientList = {}
//我的客户接口数据
let myClient = {}
export {
    list,
    clientList,
    myClient
}

